"""Regression tests for the four review comments Codex left on PR #497.

Each was reproduced against the code first:
  1. standard Markdown (images/links) in a stranger-written PR title survived `md_cell`;
  2. a PR's history key followed its editable title, so a title edit counted as "resolved + new";
  3. broken wikilinks of an otherwise fresh hub were only in the detail table, never an item;
  4. PR state was read from ONE repo-wide `--limit 200` query, so an old worktree branch could fall out.
"""

from __future__ import annotations

import json
import os
import re
import sys
import time
from datetime import date, timedelta
from pathlib import Path

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))

import threads_center as tc  # noqa: E402

D0 = date(2026, 10, 2)


@pytest.fixture(autouse=True)
def _never_touch_the_real_home(tmp_path, monkeypatch):
    monkeypatch.setattr(Path, "home", lambda: tmp_path / "_home")


def make_ctx(tmp_path, today=D0, **kw) -> tc.Context:
    vault = kw.pop("vault", tmp_path / "vault")
    vault.mkdir(exist_ok=True)
    return tc.Context(
        today=today,
        repo=kw.pop("repo", None),
        vault=vault,
        pearl_registries=[],
        threads_file=vault / "t.md",
        log_dir=tmp_path / "logs",
        runner=kw.pop("runner", None),
        seen_file=kw.pop("seen_file", None),
        is_windows=True,
    )


# a character that begins live Markdown link/image/reference syntax, not escaped by a backslash
_LIVE_OPEN = re.compile(r"(?<!\\)\[")
_LIVE_CLOSE = re.compile(r"(?<!\\)\]")


# --------------------------------------------------------------------------- 1: Markdown in foreign text
class TestForeignMarkdownIsInert:
    @pytest.mark.parametrize(
        "title",
        [
            "![tracking](https://attacker.example/pixel)",
            "[click me](https://attacker.example/x)",
            "[a][ref] and [ref]: https://attacker.example",
            "![](https://attacker.example/p.png)",
            "PR #1: fix ![x](https://a.test/p) now",
            "[[wiki]] ![[embed]] [[a|b]]",
            "nested [[[x](y)]]",
            "[x](<https://a.test>)",
        ],
    )
    def test_no_live_link_or_image_syntax_survives(self, title):
        out = tc.md_cell(title)
        assert not _LIVE_OPEN.search(out), out
        assert not _LIVE_CLOSE.search(out), out

    def test_an_image_cannot_be_rebuilt_from_the_escaped_text(self):
        out = tc.md_cell("![tracking](https://attacker.example/pixel)")
        # `\](` still contains the substring "](", but the backslash makes the bracket literal text
        assert not _LIVE_OPEN.search(out) and not _LIVE_CLOSE.search(out)
        assert out.startswith("!\\[") and "\\](" in out  # the characters are still readable text

    def test_the_visible_text_is_preserved_for_a_human_reader(self):
        out = tc.md_cell("[automated] chore: x")
        assert out == "\\[automated\\] chore: x"

    @given(st.text(max_size=200))
    @settings(max_examples=200, deadline=None)
    def test_no_input_can_leave_a_live_bracket(self, text):
        out = tc.md_cell(text)
        assert not _LIVE_OPEN.search(out) and not _LIVE_CLOSE.search(out)
        # and the table stays one cell
        assert len(tc._split_raw("| " + out + " |") or []) == 1

    def test_a_whole_rendered_note_holds_no_live_markdown_from_a_hostile_pr(self, tmp_path):
        hostile = tc.Item(
            "overdue", "pr", "PR #7: ![t](https://attacker.example/p) [x](https://attacker.example)",
            "CI красный", 20, ref="https://example.test/pull/7",
        )  # fmt: skip
        snap = tc.build_snapshot(make_ctx(tmp_path), (("prs", lambda c: [hostile]),))
        row = next(ln for ln in tc.render_markdown(snap).splitlines() if "PR #7" in ln)
        assert row.lstrip().startswith("| PR #7")  # it is the table row of the hostile PR
        cells = tc._split_raw(row) or []
        assert len(cells) == 4  # title | detail | age | kind: the table was not broken
        assert not _LIVE_OPEN.search(cells[0]) and not _LIVE_CLOSE.search(cells[0])
        assert "attacker.example" in cells[0]  # still visible as text, so the owner can see it

    def test_our_own_hub_wikilinks_still_work(self, tmp_path):
        snap = tc.build_snapshot(make_ctx(tmp_path), (("x", lambda c: []),))
        snap["vault_hubs"] = [
            {"hub": "mocs/A MOC.md", "age_days": 1, "header_date": "", "header_gap": None,
             "wikilinks": 1, "broken": 0, "notes": ""}
        ]  # fmt: skip
        assert "[[mocs/A MOC]]" in tc.render_markdown(snap)  # generated by us, not escaped


# --------------------------------------------------------------------------- 2: PR identity
class TestPrIdentityIsItsUrl:
    def test_a_title_edit_keeps_the_key(self):
        url = "https://github.com/o/r/pull/5"
        a = tc._item_key("pr", url, "PR #5: old title")
        b = tc._item_key("pr", url, "PR #5: a completely different title")
        assert a == b

    def test_two_pull_requests_never_share_a_key(self):
        a = tc._item_key("pr", "https://github.com/o/r/pull/5", "PR #5: x")
        b = tc._item_key("pr", "https://github.com/o/r/pull/6", "PR #5: x")
        assert a != b

    def test_the_collapsed_automated_row_without_a_url_still_ignores_its_counter(self):
        a = tc._item_key("pr", "", "14 автоматических PR (FocusOS и т.п.) не рассмотрены")
        b = tc._item_key("pr", "", "13 автоматических PR (FocusOS и т.п.) не рассмотрены")
        assert a == b

    def test_a_pr_with_an_edited_title_is_not_counted_as_resolved(self, tmp_path):
        f = tmp_path / "s.json"
        url = "https://example.test/pull/5"
        old = tc.Item("overdue", "pr", "PR #5: old title", "x", 20, ref=url)
        new = tc.Item("overdue", "pr", "PR #5: edited title", "x", 27, ref=url)
        for off, row in ((0, old), (7, new), (14, new), (21, new), (28, new)):
            d = D0 + timedelta(days=off)
            c = make_ctx(tmp_path, d, seen_file=f)
            tc.update_seen(f, tc.build_snapshot(c, (("prs", lambda c, r=row: [r]),)), d)
        data = json.loads(f.read_text(encoding="utf-8"))
        assert len(data["items"]) == 1 and not any(e.get("gone") for e in data["items"].values())
        st_ = tc.seen_stats(f, D0 + timedelta(days=28))
        assert st_["judged"] == 1 and st_["gone"] == 0  # one live PR, never "resolved"

    def test_the_overdue_age_is_not_reset_by_a_title_edit(self, tmp_path):
        f = tmp_path / "s.json"
        url = "https://example.test/pull/5"
        for off, title in ((0, "PR #5: a"), (10, "PR #5: b")):
            d = D0 + timedelta(days=off)
            c = make_ctx(tmp_path, d, seen_file=f)
            tc.update_seen(
                f,
                tc.build_snapshot(
                    c,
                    (("prs", lambda c, t=title: [tc.Item("overdue", "pr", t, "x", 20, ref=url)]),),
                ),
                d,
            )
        e = next(iter(json.loads(f.read_text(encoding="utf-8"))["items"].values()))
        assert e["overdue_since"] == D0.isoformat() and e["first_seen"] == D0.isoformat()


# --------------------------------------------------------------------------- 3: broken links are reported
class TestBrokenLinksBecomeAnItem:
    def build(self, tmp_path, text):
        v = tmp_path / "vault"
        (v / "mocs").mkdir(parents=True)
        (v / "exists.md").write_text("x", encoding="utf-8")
        hub = v / "mocs" / "A.md"
        hub.write_text(text, encoding="utf-8")
        now = time.time()
        os.utime(hub, (now, now))  # a fresh hub
        return make_ctx(tmp_path, today=tc._local_date(now), vault=v)

    def test_a_fresh_linked_hub_with_broken_links_is_not_silent(self, tmp_path):
        ctx = self.build(tmp_path, "[[exists]] [[ghost1]] [[ghost2]]")
        items = tc.collect_vault(ctx)
        broken = [i for i in items if "битыми wikilinks" in i.title]
        assert len(broken) == 1 and broken[0].section == "open"
        assert "всего 2" in broken[0].title and "mocs/A.md (2)" in broken[0].detail

    def test_the_item_reaches_the_counts_and_the_alert_summary(self, tmp_path):
        ctx = self.build(tmp_path, "[[exists]] [[ghost]]")
        snap = tc.build_snapshot(ctx, (("vault", tc.collect_vault),))
        assert snap["counts"]["open"] == 1
        assert "ОТКРЫТО 1" in tc._headline(snap)

    def test_a_hub_with_only_good_links_produces_no_such_item(self, tmp_path):
        ctx = self.build(tmp_path, "[[exists]] [[exists]]")
        assert not [i for i in tc.collect_vault(ctx) if "битыми" in i.title]

    def test_hubs_are_ranked_by_how_many_links_are_broken(self, tmp_path):
        ctx = self.build(tmp_path, "[[a1]] [[a2]] [[a3]]")
        other = ctx.vault / "mocs" / "B.md"
        other.write_text("[[b1]]", encoding="utf-8")
        now = time.time()
        os.utime(other, (now, now))
        item = next(i for i in tc.collect_vault(ctx) if "битыми" in i.title)
        assert item.detail.index("mocs/A.md (3)") < item.detail.index("mocs/B.md (1)")
        assert "2 хабов" in item.title and "всего 4" in item.title

    def test_the_title_counters_do_not_split_the_history_identity(self):
        a = tc._item_key("vault", "vault hubs", "Obsidian: 2 хабов с битыми wikilinks (всего 4)")
        b = tc._item_key("vault", "vault hubs", "Obsidian: 3 хабов с битыми wikilinks (всего 9)")
        assert a == b

    def test_the_item_has_a_legend_and_a_collector(self):
        assert "vault" in tc.KIND_LEGEND and tc.KIND_COLLECTOR["vault"] == ("vault",)


# --------------------------------------------------------------------------- 4: one PR query per branch
class TestPrStateIsReadPerBranch:
    def runner(self, tmp_path, branches, answers, seen):
        porcelain = "".join(
            f"worktree {tmp_path / b.replace('/', '_')}\nHEAD 1\nbranch refs/heads/{b}\n\n"
            for b in branches
        )

        def run(cmd, timeout=60):
            seen.append(cmd)
            if cmd[0] == "git" and "worktree" in cmd:
                return 0, porcelain
            if cmd[0] == "git":
                return 0, ""
            if "--head" in cmd:
                head = cmd[cmd.index("--head") + 1]
                return answers.get(head, (0, "[]"))
            return 1, ""

        return run

    def test_one_query_per_branch_with_head_and_no_repo_wide_limit(self, tmp_path):
        seen: list[list[str]] = []
        run = self.runner(tmp_path, ["main", "feat/a", "fix/b"], {}, seen)
        tc.collect_git(make_ctx(tmp_path, repo=tmp_path, runner=run))
        gh = [c for c in seen if c[0] == "gh"]
        heads = sorted(c[c.index("--head") + 1] for c in gh)
        assert heads == ["feat/a", "fix/b"]  # main is never asked about
        assert not any("200" in c for c in gh)

    def test_an_old_branch_is_found_however_many_newer_prs_exist(self, tmp_path):
        """The old repo-wide query returned only the newest 200 PRs; this branch's PR is far older."""
        seen: list[list[str]] = []
        answers = {
            "old/branch": (0, json.dumps([{"headRefName": "old/branch", "state": "CLOSED"}]))
        }
        run = self.runner(tmp_path, ["old/branch"], answers, seen)
        items = tc.collect_git(make_ctx(tmp_path, repo=tmp_path, runner=run))
        assert any("old/branch закрыт без мержа" in i.title for i in items)

    @pytest.mark.parametrize(
        ("states", "reported"),
        [
            (["CLOSED"], True),
            (["CLOSED", "CLOSED"], True),
            (["CLOSED", "MERGED"], False),  # an earlier attempt was closed, a later one merged
            (["MERGED"], False),
            (["OPEN"], False),
            (["CLOSED", "OPEN"], False),
            ([], False),  # never had a PR: nothing to report
        ],
    )
    def test_only_a_branch_whose_prs_were_all_closed_unmerged_is_reported(
        self, tmp_path, states, reported
    ):
        answers = {
            "feat/x": (0, json.dumps([{"headRefName": "feat/x", "state": s} for s in states]))
        }
        run = self.runner(tmp_path, ["feat/x"], answers, [])
        items = tc.collect_git(make_ctx(tmp_path, repo=tmp_path, runner=run))
        assert any("закрыт без мержа" in i.title for i in items) is reported

    def test_a_pr_of_another_branch_in_the_answer_is_ignored(self, tmp_path):
        answers = {"feat/x": (0, json.dumps([{"headRefName": "someone/else", "state": "CLOSED"}]))}
        run = self.runner(tmp_path, ["feat/x"], answers, [])
        assert not [
            i
            for i in tc.collect_git(make_ctx(tmp_path, repo=tmp_path, runner=run))
            if "закрыт" in i.title
        ]

    def test_a_failed_query_is_a_warning_and_does_not_hide_the_other_branches(self, tmp_path):
        answers = {
            "feat/a": (1, ""),
            "feat/b": (0, json.dumps([{"headRefName": "feat/b", "state": "CLOSED"}])),
        }
        run = self.runner(tmp_path, ["feat/a", "feat/b"], answers, [])
        ctx = make_ctx(tmp_path, repo=tmp_path, runner=run)
        items = tc.collect_git(ctx)
        assert any("feat/b закрыт без мержа" in i.title for i in items)
        assert any("проверка закрытых PR пропущена" in w for w in ctx.cache["warnings"])

    @pytest.mark.parametrize("bad", ["not json", "{}", "null", '"x"', "[1, 2]"])
    def test_garbage_output_is_a_warning_not_a_crash(self, tmp_path, bad):
        run = self.runner(tmp_path, ["feat/x"], {"feat/x": (0, bad)}, [])
        ctx = make_ctx(tmp_path, repo=tmp_path, runner=run)
        tc.collect_git(ctx)
        assert any("не разобран" in w for w in ctx.cache["warnings"])

    def test_detached_head_and_main_cost_no_github_calls(self, tmp_path):
        seen: list[list[str]] = []
        porcelain = f"worktree {tmp_path}\nHEAD 1\ndetached\n\nworktree {tmp_path / 'm'}\nHEAD 2\nbranch refs/heads/master\n"

        def run(cmd, timeout=60):
            seen.append(cmd)
            return (0, porcelain) if cmd[0] == "git" and "worktree" in cmd else (0, "")

        tc.collect_git(make_ctx(tmp_path, repo=tmp_path, runner=run))
        assert not [c for c in seen if c[0] == "gh" and "--head" in c]

    def test_the_query_stays_pinned_to_the_repo_with_dash_r(self, tmp_path):
        seen: list[list[str]] = []

        def run(cmd, timeout=60):
            seen.append(cmd)
            if cmd[0] == "git" and "worktree" in cmd:
                return 0, f"worktree {tmp_path}\nHEAD 1\nbranch refs/heads/feat/x\n"
            if cmd[0] == "git" and "remote" in cmd:
                return 0, "git@github.com:owner/name.git\n"
            return (0, "") if cmd[0] == "git" else (0, "[]")

        tc.collect_git(make_ctx(tmp_path, repo=tmp_path, runner=run))
        gh = next(c for c in seen if c[0] == "gh")
        assert gh[-2:] == ["-R", "owner/name"] and "--head" in gh
