"""Property-based (hypothesis) tests for the shell-command parsers in
hooks/lib/security.py.

WHY: hand-written fixtures (tests/test_hooks.py::TestShellTokenize) pin down
specific known-tricky cases (quote-splitting, force-redirect, heredocs), but
they can only encode edge cases someone already thought of. The escape-aware
pipe-table parser bug backported into research_health_loop.py on 2026-09-01
(26/193 real rows mis-read for years before anyone noticed) is exactly the
failure mode property-based testing exists to catch: a parser that is
correct on every case its author imagined, and wrong on inputs generated by
letting a search process explore the space instead. This file is the first
property-based coverage in this repo (see Frontier Agent Engineering 2026
gap analysis, Obsidian note, 2026-09-02) applied to the two most
security-critical parsers already in the codebase.

Scope: crash-safety (never raise on ANY input) and quote/escape-boundary
invariants (a chain operator legitimately inside quotes or escaped must
never cause a split) for `_quote_aware_chain_split`, `split_shell_statements`,
`shell_statement_tokens`, and `shell_command_tokens`.
"""

from __future__ import annotations

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st
from lib.security import (
    _quote_aware_chain_split,
    shell_command_tokens,
    shell_statement_tokens,
    split_shell_statements,
)

pytestmark = pytest.mark.security

# WHY exclude quote/backslash/chain-operator characters from the "safe inner
# text" alphabet: this generates text that is guaranteed NOT to contain any
# character _quote_aware_chain_split treats specially on its own, so it can
# be safely embedded inside a quoted region without accidentally creating a
# second, unintended quote boundary or an accidental escape sequence.
_SAFE_INNER_TEXT = st.text(
    alphabet=st.characters(blacklist_characters="'\"\\&|;\n"),
    max_size=40,
).filter(lambda t: "IFS" not in t.upper())
# WHY the extra .filter(), added 2026-09 alongside the $IFS-normalization
# fix in hooks/lib/security.py: unquoted $IFS/${IFS} is no longer inert
# text by design (it undergoes bash word-splitting exactly like a literal
# space -- a real filter-bypass technique, see _normalize_unquoted_ifs's
# own docstring), so Hypothesis correctly found `$IFS` as a genuine
# counter-example to "identity invariant" tests below that assumed ALL
# text without quote/chain-operator characters passes through byte-for-byte
# unchanged. That assumption is now knowingly false for IFS-substitution
# text -- the fix's entire point -- so this generator excludes it rather
# than the identity tests being weakened or deleted (Test Protection hard
# rule: fix the code or narrow the precondition, never silence the test).

# Text that MAY contain any of the chain-operator characters, to be placed
# INSIDE a quoted region -- these must never trigger a split there.
_ADVERSARIAL_INNER_TEXT = st.text(
    alphabet=st.characters(blacklist_characters="'\"\\"),
    max_size=40,
)

_ARBITRARY_TEXT = st.text(max_size=200)


class TestCrashSafety:
    """No amount of adversarial or malformed input may raise an exception --
    these are security gates; an unhandled exception here would either crash
    the hook (denial of service against the hook itself) or, worse, abort
    before the security check it was performing ever completed."""

    @given(text=_ARBITRARY_TEXT)
    @settings(max_examples=300)
    def test_quote_aware_chain_split_never_raises(self, text: str) -> None:
        result = _quote_aware_chain_split(text)
        assert isinstance(result, list)
        assert all(isinstance(p, str) for p in result)

    @given(text=_ARBITRARY_TEXT)
    @settings(max_examples=300)
    def test_split_shell_statements_never_raises(self, text: str) -> None:
        result = split_shell_statements(text)
        assert isinstance(result, list)
        assert all(isinstance(s, str) for s in result)

    @given(text=_ARBITRARY_TEXT)
    @settings(max_examples=300)
    def test_shell_statement_tokens_never_raises(self, text: str) -> None:
        result = shell_statement_tokens(text)
        assert isinstance(result, list)
        assert all(isinstance(t, str) for t in result)

    @given(text=_ARBITRARY_TEXT)
    @settings(max_examples=300)
    def test_shell_command_tokens_never_raises(self, text: str) -> None:
        result = shell_command_tokens(text)
        assert isinstance(result, list)
        assert all(isinstance(t, str) for t in result)


class TestQuoteBoundaryInvariant:
    """A chain operator (&&, ||, ;, |, &) inside a matched quote pair is
    cell/argument CONTENT, not a statement boundary -- this is the exact
    invariant the 2026-08-24 rewrite (see _quote_aware_chain_split's own WHY
    comment) fixed a regex-based implementation for violating."""

    @given(inner=_ADVERSARIAL_INNER_TEXT)
    @settings(max_examples=300)
    def test_double_quoted_adversarial_content_never_splits(self, inner: str) -> None:
        line = f'echo x > "{inner}"'
        result = _quote_aware_chain_split(line)
        # A properly quoted region containing chain-operator-like characters
        # must survive as ONE part -- the whole line, no split at all.
        assert result == [line]

    @given(inner=_ADVERSARIAL_INNER_TEXT)
    @settings(max_examples=300)
    def test_single_quoted_adversarial_content_never_splits(self, inner: str) -> None:
        line = f"echo x > '{inner}'"
        result = _quote_aware_chain_split(line)
        assert result == [line]


class TestIdentityInvariant:
    """Text containing none of the parser's special characters must pass
    through completely unchanged -- the parser should never rewrite or drop
    content it has no reason to touch."""

    @given(text=_SAFE_INNER_TEXT)
    @settings(max_examples=300)
    def test_plain_text_passes_through_chain_split_unchanged(self, text: str) -> None:
        assert _quote_aware_chain_split(text) == [text]

    @given(text=_SAFE_INNER_TEXT)
    @settings(max_examples=300)
    def test_plain_single_line_command_is_one_statement(self, text: str) -> None:
        stripped = text.strip()
        if not stripped:
            return  # split_shell_statements drops blank statements by design
        assert split_shell_statements(text) == [text]
