#!/usr/bin/env python3
"""SubagentStop hook: ACE Reflector — incremental playbook learning.

Based on: ACE (Agentive Context Engineering), arXiv:2510.04618
WHY: pattern_extractor fires only on fix: commits. ACE Reflector fires on
every SubagentStop, capturing approach effectiveness across ALL task types.
Delta updates (not full rewrites) preserve accumulated knowledge across sessions.

ACE roles mapped to our system:
  Generator  → builder/explorer/tester agents
  Reflector  → this hook
  Curator    → playbook.md (sorted by net score: helpful - harmful)
"""

import sys
from pathlib import Path

from utils import hook_main, parse_stdin

PLAYBOOK_PATH = Path.home() / ".claude" / "memory" / "playbook.md"
MIN_RESPONSE_LEN = 30
MAX_ENTRIES = 50  # WHY: prevent unbounded growth — keep only top-N by net score


# --- Outcome detection -------------------------------------------------------

_FAILURE_SIGNALS = (
    "error:",
    "failed",
    "exception",
    "traceback",
    "not found",
    "cannot",
    "couldn't",
    "does not exist",
    "no such file",
)
_SUCCESS_SIGNALS = (
    "completed",
    "done",
    "finished",
    "passed",
    "created",
    "added",
    "fixed",
    "updated",
    "success",
)


def _extract_outcome(message: str) -> tuple[str, bool]:
    """Return (short_summary, is_success) from agent message.

    WHY: explicit failure signals take priority over success signals —
    an agent can say "done" and still have an error in the traceback.
    """
    msg_lower = message.lower()
    has_failure = any(s in msg_lower for s in _FAILURE_SIGNALS)
    has_success = any(s in msg_lower for s in _SUCCESS_SIGNALS)
    is_success = has_success and not has_failure
    summary = message.strip().split("\n")[0][:120]
    return summary, is_success


# --- Approach classification --------------------------------------------------

_APPROACH_KEYWORDS: list[tuple[str, list[str]]] = [
    ("test-driven", ["pytest", "assert", "test_", "failing test"]),
    ("search-first", ["grep", "glob", "rg ", "find ", "search"]),
    ("explore-first", ["read", "explore", "understand", "context"]),
    ("direct-implementation", ["edit", "write", "create", "implement", "add "]),
    ("debug", ["traceback", "error", "fix", "diagnose", "root cause"]),
]


def _classify_approach(message: str) -> str:
    """Return the dominant approach keyword for this agent run.

    WHY: approach classification aggregates across tasks, not per-task —
    this reveals which workflows succeed most over time (ACE insight).
    """
    msg_lower = message.lower()
    for approach, keywords in _APPROACH_KEYWORDS:
        if any(k in msg_lower for k in keywords):
            return approach
    return "general"


# --- Playbook I/O ------------------------------------------------------------


def _load_playbook() -> dict[str, dict]:
    """Parse playbook.md into {approach: {helpful, harmful, example}}."""
    if not PLAYBOOK_PATH.exists():
        return {}

    entries: dict[str, dict] = {}
    current_key: str | None = None

    for line in PLAYBOOK_PATH.read_text(encoding="utf-8").splitlines():
        if line.startswith("### "):
            current_key = line[4:].strip()
            entries[current_key] = {"helpful": 0, "harmful": 0, "example": ""}
        elif current_key:
            if line.startswith("- helpful:"):
                try:
                    entries[current_key]["helpful"] = int(line.split(":")[1].strip())
                except (ValueError, IndexError):
                    pass
            elif line.startswith("- harmful:"):
                try:
                    entries[current_key]["harmful"] = int(line.split(":")[1].strip())
                except (ValueError, IndexError):
                    pass
            elif line.startswith("- example:"):
                entries[current_key]["example"] = line.split(":", 1)[1].strip()

    return entries


def _save_playbook(entries: dict[str, dict]) -> None:
    """Write playbook.md, sorted by net score (helpful - harmful) descending."""
    PLAYBOOK_PATH.parent.mkdir(parents=True, exist_ok=True)

    # WHY: net score = helpful - harmful. High net score = reliably effective approach.
    ranked = sorted(
        entries.items(),
        key=lambda x: x[1].get("helpful", 0) - x[1].get("harmful", 0),
        reverse=True,
    )

    lines = [
        "# ACE Playbook\n\n",
        "_Auto-generated by ace_reflector.py. Delta updates only — do not hand-edit._\n\n",
    ]
    for key, data in ranked[:MAX_ENTRIES]:
        lines.append(f"### {key}\n")
        lines.append(f"- helpful: {data.get('helpful', 0)}\n")
        lines.append(f"- harmful: {data.get('harmful', 0)}\n")
        lines.append(f"- example: {data.get('example', '')}\n")
        lines.append("\n")

    PLAYBOOK_PATH.write_text("".join(lines), encoding="utf-8")


# --- Main --------------------------------------------------------------------


def main() -> None:
    data = parse_stdin()
    message: str = data.get("last_assistant_message", "")

    if not message or len(message) < MIN_RESPONSE_LEN:
        sys.exit(0)

    summary, is_success = _extract_outcome(message)
    approach = _classify_approach(message)

    entries = _load_playbook()

    if approach not in entries:
        entries[approach] = {"helpful": 0, "harmful": 0, "example": ""}

    # WHY: delta update — increment only the relevant counter, not rewrite.
    # This is the key ACE insight: local edits preserve past learning.
    if is_success:
        entries[approach]["helpful"] += 1
        # Only update example on success — prefer positive demonstrations
        if summary:
            entries[approach]["example"] = summary
    else:
        entries[approach]["harmful"] += 1

    _save_playbook(entries)

    status = "helpful+1" if is_success else "harmful+1"
    print(f"[ace-reflector] {status} | approach={approach}", file=sys.stderr)


if __name__ == "__main__":
    hook_main(main)
