#!/usr/bin/env python3
"""Universal event-level observability hook.

Inspired by disler/claude-code-hooks-multi-agent-observability (1448★):
one lightweight logger registered on the main event types, recording WHICH
event fired + which tool, without touching the 65 existing hooks that don't
self-log.

WHY this design (not 65 edits):
- 65/71 hooks don't call log_hook_trigger → editing each is risky + slow.
- This single hook gives EVENT-level telemetry (how often each event/tool
  fires) at zero risk to existing hooks.
- It does NOT replace per-hook log_hook_trigger (that stays for the 6 detailed
  ones). It writes to a SEPARATE log (hook_events.jsonl) to avoid mixing.

What it covers / does NOT cover:
- ✅ "How often does PostToolUse fire? On which tools?" (event-level)
- ❌ "Which of the 10 PostToolUse hooks fired?" (needs per-hook logging — tier-2)

Recursion guard: respects CLAUDE_INVOKED_BY.
"""

from __future__ import annotations

import json
import os
import sys
from datetime import UTC, datetime
from pathlib import Path

from utils import rotate_log_if_large

# Recursion guard — never log events generated by our own sub-agents
if os.environ.get("CLAUDE_INVOKED_BY"):
    sys.exit(0)

LOG_FILE = Path.home() / ".claude" / "logs" / "hook_events.jsonl"


def main() -> int:
    try:
        raw = sys.stdin.read()
    except Exception:
        sys.exit(0)

    if not raw.strip():
        sys.exit(0)

    try:
        data = json.loads(raw)
    except (json.JSONDecodeError, ValueError):
        sys.exit(0)

    # Extract minimal, non-sensitive metadata only
    event = data.get("hook_event_name") or data.get("hookEventName") or "unknown"
    tool = data.get("tool_name") or data.get("toolName") or ""

    entry = {
        "ts": datetime.now(UTC).isoformat(),
        "event": event,
        "tool": tool,
    }

    try:
        LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
        rotate_log_if_large(LOG_FILE)
        with LOG_FILE.open("a", encoding="utf-8") as f:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    except OSError:
        pass

    # Never block — observability is passive
    sys.exit(0)


if __name__ == "__main__":
    main()
